"""A2A modülü - ajanlar arası iletişim için SDK yardımcıları."""

from src.a2a.helpers import (
    A2AQueryPayload,
    build_agent_card,
    build_agent_response_task,
    build_department_response_task,
    build_query_task,
    build_text_artifact,
    build_text_message,
    extract_agent_response,
    extract_department_response,
)
from src.a2a.external import (
    ExternalAgentValidationRequest,
    ExternalAgentValidationResult,
    authorize_external_a2a_request,
    validate_external_agent,
)
from src.a2a.responses import (
    AgentResponse,
    agent_response_to_department_response,
    build_failed_agent_response,
    department_response_to_agent_response,
    validate_agent_response,
    validate_legacy_department_response,
)
from src.a2a.tracing import (
    PARENT_SPAN_ID_KEY,
    SPAN_ID_KEY,
    TRACE_ID_KEY,
    TRACE_METADATA_KEYS,
    child_trace_metadata,
    ensure_trace_metadata,
    new_span_id,
    new_trace_id,
    trace_metadata,
)
from src.a2a.schemas import (
    AGENT_RESPONSE_SCHEMA,
    DEPARTMENT_RESPONSE_SCHEMA,
    USER_QUERY_RESPONSE_SCHEMA,
)
from src.a2a.state import (
    STATE_TRANSITIONS_METADATA_KEY,
    build_state_transition,
    metadata_state_transitions,
    response_state_transitions,
    submitted_transition_from_message,
    task_state_transitions,
)
from src.a2a.targets import (
    AgentServiceTarget,
    SpecialistTarget,
    agent_target_department,
    agent_target_kind,
    resolve_agent_service_target,
)

__all__ = [
    "A2AQueryPayload",
    "AGENT_RESPONSE_SCHEMA",
    "AgentResponse",
    "AgentServiceTarget",
    "ExternalAgentValidationRequest",
    "ExternalAgentValidationResult",
    "DEPARTMENT_RESPONSE_SCHEMA",
    "SpecialistTarget",
    "PARENT_SPAN_ID_KEY",
    "SPAN_ID_KEY",
    "STATE_TRANSITIONS_METADATA_KEY",
    "TRACE_ID_KEY",
    "TRACE_METADATA_KEYS",
    "USER_QUERY_RESPONSE_SCHEMA",
    "agent_response_to_department_response",
    "agent_target_department",
    "agent_target_kind",
    "authorize_external_a2a_request",
    "build_agent_card",
    "build_agent_response_task",
    "build_department_response_task",
    "build_failed_agent_response",
    "build_query_task",
    "build_state_transition",
    "build_text_artifact",
    "build_text_message",
    "child_trace_metadata",
    "department_response_to_agent_response",
    "ensure_trace_metadata",
    "extract_agent_response",
    "extract_department_response",
    "metadata_state_transitions",
    "new_span_id",
    "new_trace_id",
    "response_state_transitions",
    "resolve_agent_service_target",
    "submitted_transition_from_message",
    "task_state_transitions",
    "trace_metadata",
    "validate_agent_response",
    "validate_external_agent",
    "validate_legacy_department_response",
]
