"""initial schema from new ddl

Revision ID: e1f257054c4e
Revises: 
Create Date: 2026-03-05 00:38:26.223682
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f257054c4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_index(op.f('ix_agent_registry_department'), 'agent_registry', ['department'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('faculty', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('available_scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_amount', sa.Float(), nullable=True),
    sa.Column('min_gpa', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('course_registration_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_name', sa.String(length=120), nullable=False),
    sa.Column('credits', sa.SmallInteger(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('instructor', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_index(op.f('ix_courses_department'), 'courses', ['department'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('faculty', sa.String(length=80), nullable=False),
    sa.Column('class_year', sa.SmallInteger(), nullable=False),
    sa.Column('enrollment_year', sa.SmallInteger(), nullable=False),
    sa.Column('registration_status', sa.String(length=30), nullable=False),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('total_credits', sa.SmallInteger(), nullable=False),
    sa.Column('completed_credits', sa.SmallInteger(), nullable=False),
    sa.Column('current_semester', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_students_department'), 'students', ['department'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'prerequisite_id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_student_id'), 'otp_codes', ['student_id'], unique=False)
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=True),
    sa.Column('routing_strategy', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_registry.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_logs_agent_id'), 'query_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_query_logs_student_id'), 'query_logs', ['student_id'], unique=False)
    op.create_table('scholarship_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('available_scholarship_id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['available_scholarship_id'], ['available_scholarships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarship_applications_student_id'), 'scholarship_applications', ['student_id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('available_scholarship_id', sa.Integer(), nullable=False),
    sa.Column('monthly_amount', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['available_scholarship_id'], ['available_scholarships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_student_id'), 'scholarships', ['student_id'], unique=False)
    op.create_table('slack_student_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slack_user_id')
    )
    op.create_index(op.f('ix_slack_student_mapping_student_id'), 'slack_student_mapping', ['student_id'], unique=False)
    op.create_table('student_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_courses_course_id'), 'student_courses', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_courses_student_id'), 'student_courses', ['student_id'], unique=False)
    op.create_table('tuition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('has_debt', sa.Boolean(), nullable=False),
    sa.Column('debt_amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('last_payment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuition_student_id'), 'tuition', ['student_id'], unique=False)
    op.create_table('verification_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=50), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_verification_sessions_student_id'), 'verification_sessions', ['student_id'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('query_log_id', sa.Integer(), nullable=True),
    sa.Column('sender_agent_id', sa.Integer(), nullable=False),
    sa.Column('receiver_agent_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_log_id'], ['query_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_agent_id'], ['agent_registry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agent_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_agent_tasks_query_log_id'), 'agent_tasks', ['query_log_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_receiver_agent_id'), 'agent_tasks', ['receiver_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_sender_agent_id'), 'agent_tasks', ['sender_agent_id'], unique=False)
    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tuition_id', sa.Integer(), nullable=False),
    sa.Column('installment_number', sa.SmallInteger(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tuition_id'], ['tuition.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installments_tuition_id'), 'installments', ['tuition_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tuition_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tuition_id'], ['tuition.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    op.create_index(op.f('ix_payments_tuition_id'), 'payments', ['tuition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_tuition_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_installments_tuition_id'), table_name='installments')
    op.drop_table('installments')
    op.drop_index(op.f('ix_agent_tasks_sender_agent_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_receiver_agent_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_query_log_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_verification_sessions_student_id'), table_name='verification_sessions')
    op.drop_table('verification_sessions')
    op.drop_index(op.f('ix_tuition_student_id'), table_name='tuition')
    op.drop_table('tuition')
    op.drop_index(op.f('ix_student_courses_student_id'), table_name='student_courses')
    op.drop_index(op.f('ix_student_courses_course_id'), table_name='student_courses')
    op.drop_table('student_courses')
    op.drop_index(op.f('ix_slack_student_mapping_student_id'), table_name='slack_student_mapping')
    op.drop_table('slack_student_mapping')
    op.drop_index(op.f('ix_scholarships_student_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_scholarship_applications_student_id'), table_name='scholarship_applications')
    op.drop_table('scholarship_applications')
    op.drop_index(op.f('ix_query_logs_student_id'), table_name='query_logs')
    op.drop_index(op.f('ix_query_logs_agent_id'), table_name='query_logs')
    op.drop_table('query_logs')
    op.drop_index(op.f('ix_otp_codes_student_id'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_department'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_courses_department'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_table('course_registration_periods')
    op.drop_table('available_scholarships')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_agent_registry_department'), table_name='agent_registry')
    op.drop_table('agent_registry')
    # ### end Alembic commands ###
