"""Compare reranker benchmark JSON reports.

This script is intentionally lightweight: it reads reports generated by
scripts.analyze_reranker_scores and produces a Markdown summary. It does not
load models or touch production settings.
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any


_BENCHMARK_SOURCE_OWNER_MARKERS: tuple[tuple[str, tuple[str, ...]], ...] = (
    (
        "tuition_fee_catalog",
        ("katki_payi", "katkı_payı", "ogrenim_ucreti", "öğrenim_ücreti", "harc", "ucret", "ücret"),
    ),
    (
        "international_policy",
        ("uluslararasi", "uluslararası", "yabanci", "yabancı", "yos", "yös", "tomer", "tömer", "ikamet"),
    ),
    (
        "curriculum_catalog",
        ("mufredat", "müfredat", "ders_plani", "ders_planı", "akts", "curriculum"),
    ),
    (
        "student_affairs_policy",
        (
            "sik_sorulan_sorular",
            "sık_sorulan_sorular",
            "ogrenci_isleri",
            "öğrenci_işleri",
            "yonerge",
            "yönerge",
            "yonetmelik",
            "yönetmelik",
            "on_lisans",
            "ön_lisans",
            "onlisans",
            "önlisans",
            "yatay_gecis",
            "yatay_geçiş",
            "cift_anadal",
            "çift_anadal",
            "cift_ana_dal",
            "çift_ana_dal",
            "yandal",
            "yan_dal",
            "staj",
            "yaz_okulu",
            "muafiyet",
            "intibak",
            "kimlik_karti",
            "kimlik_kartı",
            "bagil_degerlendirme",
            "bağıl_değerlendirme",
        ),
    ),
)

_EXPECTED_DEPARTMENT_OWNER_MAP: dict[str, set[str]] = {
    "student_affairs": {"student_affairs_policy", "academic_calendar"},
    "finance": {"tuition_fee_catalog", "student_affairs_policy"},
    "academic_programs": {"curriculum_catalog", "international_policy", "student_affairs_policy"},
}


def _load_report(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        data = json.load(handle)
    data["_path"] = str(path)
    data["_label"] = path.stem
    return data


def _normal(text: str | None) -> str:
    return (text or "").strip().casefold()


def _infer_owner(result: dict[str, Any] | None) -> str:
    if not result:
        return "-"
    existing = str(result.get("source_owner") or result.get("source_family") or "").strip()
    if existing:
        return existing
    haystack = _normal(f"{result.get('source') or ''} {result.get('content_preview') or ''}")
    for owner, markers in _BENCHMARK_SOURCE_OWNER_MARKERS:
        if any(marker in haystack for marker in markers):
            return owner
    return "-"


def _owner_matches_expected(expected_department: str, owner: str) -> bool:
    expected_parts = [
        part.strip()
        for part in _normal(expected_department).split(",")
        if part.strip() and part.strip() not in {"?", "clarification", "announcement"}
    ]
    if not expected_parts or not owner or owner == "-":
        return False
    return any(owner in _EXPECTED_DEPARTMENT_OWNER_MAP.get(part, set()) for part in expected_parts)


def _top1(query_record: dict[str, Any]) -> dict[str, Any] | None:
    results = query_record.get("results") or []
    return results[0] if results else None


def _queries_by_text(report: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {str(item.get("query") or ""): item for item in report.get("queries") or []}


def _owner_summary(report: dict[str, Any]) -> dict[str, Any]:
    counts: dict[str, int] = {}
    checked = 0
    matched = 0
    for item in report.get("queries") or []:
        top = _top1(item)
        if not top:
            continue
        owner = _infer_owner(top)
        counts[owner] = counts.get(owner, 0) + 1
        expected = str(item.get("department") or "")
        if expected.strip() and expected.strip() not in {"?", "clarification", "announcement"}:
            checked += 1
            if _owner_matches_expected(expected, owner):
                matched += 1
    return {
        "counts": counts,
        "checked": checked,
        "matched": matched,
    }


def _compare_top1(baseline: dict[str, Any], candidate: dict[str, Any]) -> dict[str, Any]:
    baseline_queries = _queries_by_text(baseline)
    candidate_queries = _queries_by_text(candidate)
    common = sorted(set(baseline_queries) & set(candidate_queries))
    same_source = 0
    same_owner = 0
    changed: list[dict[str, Any]] = []
    missing = sorted(set(baseline_queries) - set(candidate_queries))
    added = sorted(set(candidate_queries) - set(baseline_queries))

    for query in common:
        baseline_top = _top1(baseline_queries[query])
        candidate_top = _top1(candidate_queries[query])
        baseline_source = str((baseline_top or {}).get("source") or "-")
        candidate_source = str((candidate_top or {}).get("source") or "-")
        baseline_owner = _infer_owner(baseline_top)
        candidate_owner = _infer_owner(candidate_top)
        if baseline_source == candidate_source:
            same_source += 1
        if baseline_owner == candidate_owner:
            same_owner += 1
        if baseline_source != candidate_source or baseline_owner != candidate_owner:
            changed.append(
                {
                    "query": query,
                    "baseline_source": baseline_source,
                    "candidate_source": candidate_source,
                    "baseline_owner": baseline_owner,
                    "candidate_owner": candidate_owner,
                    "baseline_score": (baseline_top or {}).get("raw_reranker_score"),
                    "candidate_score": (candidate_top or {}).get("raw_reranker_score"),
                }
            )

    return {
        "common": len(common),
        "same_source": same_source,
        "same_owner": same_owner,
        "changed": changed,
        "missing": missing,
        "added": added,
    }


def _fmt_seconds(value: Any) -> str:
    try:
        return f"{float(value):.1f}s"
    except (TypeError, ValueError):
        return "-"


def _fmt_number(value: Any) -> str:
    try:
        return f"{float(value):.4f}"
    except (TypeError, ValueError):
        return "-"


def _model_summary(report: dict[str, Any]) -> dict[str, Any]:
    owner = _owner_summary(report)
    device = report.get("device") or {}
    dtype = report.get("torch_dtype") or {}
    calibration = report.get("calibration") or {}
    suggestion = report.get("suggestion") or {}
    top1_raw = report.get("top1_raw_stats") or {}
    raw = report.get("raw_stats") or {}
    return {
        "label": report.get("_label"),
        "model": report.get("model"),
        "elapsed": report.get("elapsed_seconds"),
        "device": device.get("resolved") or device,
        "dtype": dtype.get("resolved") or dtype,
        "runtime_shift": calibration.get("shift"),
        "runtime_scale": calibration.get("scale"),
        "suggested_shift": suggestion.get("shift"),
        "suggested_scale": suggestion.get("scale"),
        "raw_median": raw.get("median"),
        "top1_median": top1_raw.get("median"),
        "owner_matched": owner["matched"],
        "owner_checked": owner["checked"],
        "owner_counts": owner["counts"],
    }


def build_markdown_report(baseline: dict[str, Any], candidates: list[dict[str, Any]]) -> str:
    reports = [baseline, *candidates]
    summaries = [_model_summary(report) for report in reports]
    comparisons = [(candidate, _compare_top1(baseline, candidate)) for candidate in candidates]

    lines: list[str] = [
        "# Reranker Report Compare",
        "",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M')}",
        f"Baseline: `{baseline.get('_label')}`",
        "",
        "## Summary",
        "",
        "| Report | Model | Device | Dtype | Elapsed | Owner match | Raw median | Top-1 median | Runtime calib | Suggested calib |",
        "|---|---|---:|---|---:|---:|---:|---:|---|---|",
    ]
    for summary in summaries:
        owner_match = f"{summary['owner_matched']}/{summary['owner_checked']}"
        runtime_calib = f"{summary['runtime_shift']}/{summary['runtime_scale']}"
        suggested_calib = f"{summary['suggested_shift']}/{summary['suggested_scale']}"
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{summary['label']}`",
                    str(summary["model"]),
                    str(summary["device"]),
                    str(summary["dtype"]),
                    _fmt_seconds(summary["elapsed"]),
                    owner_match,
                    _fmt_number(summary["raw_median"]),
                    _fmt_number(summary["top1_median"]),
                    runtime_calib,
                    suggested_calib,
                ]
            )
            + " |"
        )

    lines.extend(["", "## Top-1 Changes vs Baseline", ""])
    for candidate, comparison in comparisons:
        common = comparison["common"] or 1
        same_source = comparison["same_source"]
        same_owner = comparison["same_owner"]
        lines.extend(
            [
                f"### `{candidate.get('_label')}`",
                "",
                f"- Common queries: {comparison['common']}",
                f"- Same top-1 source: {same_source}/{comparison['common']} ({same_source / common:.1%})",
                f"- Same top-1 owner: {same_owner}/{comparison['common']} ({same_owner / common:.1%})",
                f"- Missing queries: {len(comparison['missing'])}",
                f"- Added queries: {len(comparison['added'])}",
                "",
            ]
        )
        if comparison["changed"]:
            lines.extend(
                [
                    "| Query | Baseline source | Candidate source | Baseline owner | Candidate owner | Scores |",
                    "|---|---|---|---|---|---|",
                ]
            )
            for item in comparison["changed"]:
                scores = f"{_fmt_number(item['baseline_score'])} -> {_fmt_number(item['candidate_score'])}"
                lines.append(
                    "| "
                    + " | ".join(
                        [
                            item["query"],
                            item["baseline_source"],
                            item["candidate_source"],
                            item["baseline_owner"],
                            item["candidate_owner"],
                            scores,
                        ]
                    )
                    + " |"
                )
            lines.append("")
        else:
            lines.append("No top-1 source/owner changes.")
            lines.append("")

    lines.extend(["## Owner Distribution", ""])
    for summary in summaries:
        counts = ", ".join(f"{owner}={count}" for owner, count in sorted(summary["owner_counts"].items()))
        lines.append(f"- `{summary['label']}`: {counts or '-'}")
    lines.append("")
    lines.append("Note: This report compares reranker candidate ordering only; final answer replay is still required before production switching.")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare reranker benchmark JSON reports")
    parser.add_argument("--baseline", required=True, help="Baseline JSON report")
    parser.add_argument(
        "--candidate",
        action="append",
        required=True,
        help="Candidate JSON report. Can be passed multiple times.",
    )
    parser.add_argument("--output", required=True, help="Markdown output path")
    args = parser.parse_args()

    baseline = _load_report(Path(args.baseline))
    candidates = [_load_report(Path(path)) for path in args.candidate]
    markdown = build_markdown_report(baseline, candidates)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")
    print(f"Compare report written: {output_path}")


if __name__ == "__main__":
    main()
